version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:{PORT}"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env

  mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: ["mongod", "--auth", "--bind_ip_all"]
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
  mongodb_config:

networks:
  app-network:
    driver: bridge